### ISSUE TITLE
Select widgets that will appear in Shortcake

### ISSUE THREAD

**Issue by antek83** [xwp/wp-js-widgets#45]
Hi, 
First of all great plugin as always.

I was wondering if it's there a built in way to select which widgets will be available in Shortcake..
A filter maybe or something like that.. some widgets might be considered less useful than others as post elements. 

Thanks in advance

**Comment by westonruter** [comment]
Thanks. No, there's no such filter. Also, additional enhancements are going to be focused on Gutenberg instead. So the JS Widgets plugin should be considered end-of-life'ed, though concepts from it will likely make their way into Gutenberg and core.
